### ISSUE TITLE
anyone can see you API_KEY in Network tab for dev tools

### ISSUE THREAD

**Issue by vishchi** [riwigefi/light-gpt#14]

**Comment by riwigefi** [comment]
Thank you for your reminder, my friend. As this is a pure front-end application, users access the Open AI service by sending requests within the front-end application, without using a server proxy for the Open AI service. This is to avoid the risk of user data leakage, and to allow users visiting the site to use the service directly. Therefore, I had to preset the API key, which can be viewed in the network tab through the request response. I have now obfuscated the API key, and may optimize it further in the future. Thank you very much for your reminder.

**Comment by vishchi** [comment]
Cool👍

**Comment by yiios** [comment]
> Owner

It is recommended to get a simple server-side relay, and currently see confusion is still not effective.

**Comment by vishchi** [comment]
Yes exactly man, just wrap it in an API and make this call on server side itself, so that no one can see these details on client end.

**Comment by riwigefi** [comment]
@yiios @vishchi Thank you both for your advice. I will resolve the issue of anyone being able to view the API key on the client-side as soon as possible

**Comment by vishchi** [comment]
Awesome brother!

**Comment by yiios** [comment]
> @yiios @vishchi谢谢你们的建议。我将尽快解决任何人都能够在客户端查看 API 密钥的问题

It is recommended to transit only for cases where the key is not filled in, which has two advantages.

1. reduce the pressure on the server
2. avoid the server side to use a large number of different keys for a single ip which causes OpenAI to block all these keys.

=======

建议只对不填key的情况下进行中转，这有两个好处：

1. 减轻服务器的压力
2. 避免服务端单ip大量使用不同的key导致OpenAI对这些Key都进行封禁。目前类似的行为非常容易触发封号

**Comment by riwigefi** [comment]
Great suggestion, I will make modifications based on the rules you mentioned.
