### ISSUE TITLE
Feature request: Better to have conversation saved

### ISSUE THREAD

**Issue by anc95** [riwigefi/light-gpt#16]
Thanks for your brilliant project! I really appreciate its simplicity and power. 

In regards to start conversation from last context, would it be possible to add a feature that allows for saving conversations? This would be very helpful.

**Comment by riwigefi** [comment]
Great suggestion, I will implement this feature as soon as possible.

**Comment by riwigefi** [comment]
I have now updated with a new feature that supports the "New Chat" function. The historical conversation data of the topic will be stored in the IndexedDB database, as this is a storage method with relatively large capacity on the browser-side. We hope that you will find it more comfortable to use. Just refresh site.
