### ISSUE TITLE
Adding API Key to code and allow access via username password/ google login

### ISSUE THREAD

**Issue by Pistacho261** [riwigefi/light-gpt#30]
thanks for making this app available! I like the functionalities and I would like to have it work without having to add my api key. do you think it is something possible?

Also, the mobile version sidebar is not displaying the full title, would it be worth hiding it and adding a button that makes it visible?

**Comment by yiios** [comment]
Agree, the display is currently a bit bad on mobile

**Comment by riwigefi** [comment]
Thanks for your feedback, I will correct the style bug of mobile terminal you mentioned as soon as possible. I'm adding a server proxy to enable question-and-answer conversations without an api key, so that users who don't have an api key can use it.

**Comment by Pistacho261** [comment]
thank you, how about adding a firebase container login functionality? I have tried to add it and share it but I had no success!

**Comment by riwigefi** [comment]
@daniel26191 Over the weekend, I tried the Firebase registration and login functionality as you suggested. I added the relevant features on the feat-firebase branch and was able to debug and use them successfully. However, I am not planning to merge the Firebase-related features into the master branch for now. If you need help, please refer to the code on the feat-firebase branch as it should be helpful for deploying Firebase-related features.

**Comment by Pistacho261** [comment]
Thanks for the update!
